#!/bin/sh
# abort cvmfs pull_and_push updates in progress, if any, when shutting down
# Dave Dykstra, 25 July 2013

case "$1" in
    status)
	if [ "`cl_status rscstatus 2>/dev/null`" = all ]; then
	    echo running
	else
	    echo stopped
	fi
	;;
    stop)
	pull_and_push ABORT
	;;
esac
